language: python
python:
 - "2.7"
# command to install dependencies
install:
 - sudo apt-get install python-dev
 - pip install -q Django==1.9
 - pip install -q wheel==0.24.0
 - pip install pycco
 - sudo apt-get install mongodb

# command to run tests
 - make test
# command to doc
 - make doc
# command to run server
 - make run

branches:
 -only:
  - master 