language: python
python:
 - "2.7"
# command to install dependencies
install:
 - sudo apt-get install python-dev
 - sudo apt-get install python-pip
 - pip install --upgrade pip
 - pip install -q Django==1.9
 - pip install -r requirements.txt 
 - sudo apt-get install mongodb-server mongodb-dev 
 - sudo apt-get install mongodb
# command to run tests
script:
 - make test
 - make doc

branches:
  - only:
    - master